In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
dataset -- https://drive.google.com/file/d/1cyX7Piq9jEA_VR1x4BnwqgLkDChOAqe4/view

In [3]:
df = pd.read_csv("US_honey_dataset.csv")

In [4]:
df.shape

(1115, 9)

In [5]:
df.columns

Index(['Unnamed: 0', 'state', 'colonies_number', 'yield_per_colony',
       'production', 'stocks', 'average_price', 'value_of_production', 'year'],
      dtype='object')

In [6]:
df.head()

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62.0,575000,1995
1,1,Arizona,52000,79,4108000,986000,68.0,2793000,1995
2,2,Arkansas,50000,60,3000000,900000,64.0,1920000,1995
3,3,California,420000,93,39060000,4687000,60.0,23436000,1995
4,4,Colorado,45000,60,2700000,1404000,68.0,1836000,1995

In [7]:
df = df.drop(columns = "Unnamed: 0")

''' Other methods '''
# df = df.drop(['Unnamed: 0'], axis = 1)

# df.drop(columns = "Unnamed: 0", inplace = True)
# df.drop(['Unnamed: 0'], axis = 1, inplace = True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                1115 non-null   object
 1   colonies_number      1115 non-null   int64
 2   yield_per_colony     1115 non-null   int64
 3   production           1115 non-null   int64
 4   stocks               1115 non-null   int64
 5   average_price        1115 non-null   float64
 6   value_of_production  1115 non-null   int64
 7   year                 1115 non-null   int64
dtypes: float64(1), int64(6), object(1)
memory usage: 69.8+ KB

In [9]:
df.isnull().sum()

state                  0
colonies_number        0
yield_per_colony       0
production             0
stocks                 0
average_price          0
value_of_production    0
year                   0
dtype: int64

In [11]:
# if you want direct single answer we will use this
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.duplicated().sum()

np.int64(0)

In [ ]:
--> the data is now absolutely clean

In [12]:
df.to_csv("Cleaned_honey_data.csv")

In [13]:
# Create a loop which prints the number of unique values and also the unique values inside the columns

for col in df.columns:
    print("Name of the column:",col)
    print("Number of unique values:", df[col].nunique())
    print("nunique values:",df[col].unique())
    print()

Name of the column: state
Number of unique values: 44
nunique values: ['Alabama' 'Arizona' 'Arkansas' 'California' 'Colorado' 'Florida'
 'Georgia' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'NewJersey'
 'NewMexico' 'NewYork' 'NorthCarolina' 'NorthDakota' 'Ohio' 'Oklahoma'
 'Oregon' 'Pennsylvania' 'SouthCarolina' 'SouthDakota' 'Tennessee' 'Texas'
 'Utah' 'Vermont' 'Virginia' 'Washington' 'WestVirginia' 'Wisconsin'
 'Wyoming']

Name of the column: colonies_number
Number of unique values: 189
nunique values: [ 16000  52000  50000 420000  45000 230000  70000   8000 125000  11000
  12000  17000   3000  33000   7000  97000 165000  23000 106000  60000
   9000  19000 220000  25000   5000 240000   4000  84000  32000  13000
  73000  38000  40000 390000  30000  75000 110000  58000  37000  10000
  90000 150000  22000 117000  65000  14000  15000  68000  24000  55000
  82000  34000  57000  69000 400000  35000 120000  51000   6000  85000
 145000 107000  61000  72000 245000  47000  94000  54000  79000  53000
 450000  27000  41000  80000 140000  18000 115000  64000 225000  91000
  89000  46000 505000 228000  48000 122000 255000  20000 224000 108000
  26000 440000  29000 232000 100000  43000 148000 290000 235000 105000
  39000 425000  76000 135000 136000 280000  44000  42000  67000 134000
 320000 114000 480000 210000   2000  21000 340000 200000  74000 205000
  63000 215000 116000  56000  36000 160000  59000  95000  28000 130000
 370000 380000 170000 132000 350000  49000  92000 360000  71000  77000
 355000 103000  66000 146000 270000  62000 410000 128000 157000 510000
 265000  31000 180000  87000 460000 250000  78000 330000 193000 260000
  83000 159000 162000 490000 275000 126000 310000  96000 124000 485000
 133000 335000  99000 455000  98000 119000 550000  93000 102000 118000
 173000 520000  81000 192000 101000 495000 515000  86000 137000]

Name of the column: yield_per_colony
Number of unique values: 104
nunique values: [ 58  79  60  93  86  62 129  48  74  63  68  67  44 119  45  35  92  82
  70  80  73  29  34  65  75  52 108  76  43  90  85  53 106  33  59  41
  36  64  84 105 155  51  23  32  96  77  61  46  97  83  50  78  66  95
  55 146  69  71 115  19  40 120  49 100  72  98  56 118 111  26 122 128
  37  91  89 102  81 114  22  57 104  39 112  47  94  21  87 121  42  54
  20  38  88 136 124 113  31  27 131  28 103  30 116  99]

Name of the column: production
Number of unique values: 851
nunique values: [  928000  4108000  3000000 39060000  2700000 19780000  4340000  1032000
  6000000   814000   756000  3400000  1139000   132000  3927000   495000
   245000  8924000 13530000  1120000  1541000  8480000  4380000   261000
   272000  1235000  5250000   624000 23760000  1550000   380000  2704000
  1075000   810000 20400000   212000  8904000  1056000   335000   405000
  3540000   533000  5767000  1368000  1024000  1920000  3360000 27300000
  2220000 25200000  5100000  1240000  4950000   675000  3886000   816000
   180000  3922000   230000   224000  8640000 11550000  1360000  1628000
  7020000  4875000   854000   225000  1155000  5440000   528000  1680000
   236000  3245000  1058000 23280000   320000  6806000  1564000   332000
   350000  3306000   590000  5382000  2920000   924000  2560000  3800000
 30000000  1925000 16080000  3450000  1314000  7680000   483000   568000
  3774000  1207000  4370000   152000   240000  5950000 10585000  1387000
  1848000 12840000  4087000   392000   900000  4320000   464000 24500000
  1760000   232000  2491000 15600000   372000  9964000  1664000   315000
   424000  2808000   560000  4740000  2356000  1136000  3300000  3445000
 37350000  1944000 22540000  4200000   944000   639000   828000  3900000
   736000   150000  4551000   260000   308000  6800000 11060000  1548000
  1518000 14030000  4480000   460000   539000   770000  5200000   472000
 29440000  1404000   204000  2250000 21375000   448000  7007000  1740000
   384000   296000  2958000   330000  8099000  2760000  1156000  3224000
  4628000 30300000  2052000 23256000  3315000   640000  5760000   594000
  2600000   871000  5472000   276000  6205000 11890000  1560000  8540000
  4466000   383000   440000   780000  4830000   414000 26775000  1480000
   270000  2565000  1500000 23296000   408000  8748000  1170000   396000
   234000  2664000  1248000  2360000  5115000 30800000 24360000  3135000
   784000  4700000   488000   520000  2010000  1020000   144000  4042000
   231000  5400000 13500000  1224000  1725000 12728000  4350000   385000
   960000  4640000 33350000  2448000   990000 28435000   549000  8295000
   984000   413000   294000   378000  7560000  3627000  1022000  2537000
  5655000 27625000  1430000 22000000   696000  4600000   456000   608000
  1683000   663000  4770000   220000   184000  4560000 10935000  1122000
  1525000 13872000  2064000   550000   374000  1050000  3710000   484000
 26880000  1296000   188000  1936000   969000 15275000   531000  7663000
   874000   567000   468000  2184000   455000  5427000  2926000  2394000
  4840000 23320000  1440000 20460000   952000  5700000   720000   496000
  2310000   884000   162000   451000   138000  5544000  8541000   954000
  8442000  3225000   558000  5880000   714000 24000000   159000  1911000
  1026000   470000 11475000  7638000  1298000   623000   266000  2244000
   459000  6650000  1066000  2880000 32160000 14910000  3380000   791000
   420000   280000  1888000   912000  3060000   264000    84000  4810000
  9960000  1449000   901000  9570000  3330000   190000   246000  4824000
 29580000   750000   141000  2142000  1350000 14000000  9380000  1311000
   581000   222000  3248000   376000  5698000  3159000  1044000  2280000
 17550000  1840000 20090000  3087000   768000  6300000  2345000  3430000
   217000  4355000 10125000   656000 10780000  4539000   324000   352000
  4288000   360000 30420000  2268000  1620000 22575000  8816000  1610000
  3528000  5848000  2925000   858000  1800000  2484000  1820000 13760000
  2891000  1179000  3515000   680000   512000  2464000   800000   250000
  3395000   208000  4420000  8880000  1280000  8710000  2720000   552000
   343000   540000 33670000  1035000  1638000  1568000 17380000  5964000
   546000  2805000  5312000  2240000   792000  1950000  2432000 19760000
 13770000  4662000   930000  4180000   660000   253000  3960000 10000000
  1372000   690000 10428000  3431000   333000   336000  3840000   500000
 25900000  2208000 10575000  5740000  1150000  2548000   210000  5952000
   616000 13600000 11360000  3480000   920000  3772000   357000  2106000
   244000  2581000  4608000  8840000  1575000   611000  9180000  2205000
   513000   354000  3192000 31080000  1892000 13260000  8610000   975000
  2024000  5040000  3440000  1600000  2100000 18360000  1215000 11850000
  3905000  3600000   402000  1488000   610000   156000  2233000  5183000
  9516000   583000  2412000   290000   288000  3500000 35100000   742000
  2150000  1104000   427000  4928000  1344000   252000  1804000   258000
  2379000   441000  1040000 11715000  1484000 10200000  2665000   950000
  4738000  1092000   175000  3811000   300000  7930000  1456000   517000
 10220000  2688000  3055000 34650000  1870000   840000 17820000   988000
  2728000   185000  3780000  1776000    73000   665000  6318000  1794000
   239000    92000   151000   463000   103000    67000    33000  1524000
  1774000    78000  2905000   902000   157000  1123000 12995000   346000
   377000  4765000   106000   195000    37000  1077000    40000  1556000
   282000    63000  3730000   443000   196000  1879000    98000   147000
   961000   117000    12000   471000    17000  2084000  2099000   104000
    76000  3202000   653000   135000   153000    95000  7512000   228000
   755000   306000  4290000    68000   633000   170000    43000    21000
   836000    45000  1508000   265000    65000   189000  3119000   181000
   263000   530000   145000   203000  1196000   125000    41000    24000
  1332000  1591000    64000   108000  2413000  1146000    51000    99000
  5962000   410000   845000   269000  3604000    59000   718000   209000
    53000    23000  1017000  1863000    55000   251000    66000  2505000
  1074000   637000  1036000   101000    82000  1217000    39000   490000
    27000   982000  1282000    85000  5231000    34000  1030000  6955000
   390000   257000  6381000  1689000    46000    42000  1023000    83000
  1558000    26000   193000   137000  2995000   200000  1029000   362000
   140000   850000    94000   115000   933000    56000   524000  1835000
  1426000    96000  5132000  1688000   119000    88000  9271000   256000
   767000    19000  5846000  2081000   130000    61000    57000  1167000
   255000    13000   121000  1485000   399000   832000   221000    71000
  1082000   155000   165000   107000   348000    47000  1984000  2157000
    87000    52000  3757000  1450000   207000   899000  9428000   809000
    38000  9379000  1164000    62000    50000  1221000    32000  1603000
   146000  2009000   538000   127000  1253000    77000   746000    54000
    48000   301000  1709000  1390000   113000    30000  3183000   198000
    89000  6809000   664000   622000    36000 12127000    69000  2607000
   169000   412000  1205000    22000    97000   197000  2198000   284000
   529000    25000  1045000   167000   158000   279000   822000  1016000
   124000  2506000   423000   766000  4377000   657000   998000   177000
  6541000    75000  2297000  1594000   683000   186000    14000   109000
  3022000   283000   737000    18000   655000  1005000  1161000    70000
  3680000   833000  4752000   491000  1009000   309000    15000  5154000
    35000   563000   711000    44000   201000   176000  3216000   830000
   370000   677000   116000   171000   428000   110000  1363000  3063000
  5802000   223000  1027000   118000  6422000   442000  1141000   409000
  7582000    91000  1663000    49000  1191000   692000  2752000   883000
    79000   149000  1259000   164000    58000  1384000  2495000   100000
  3208000   844000   123000  8108000   576000  1102000  8668000   798000
   855000   112000   368000  1627000   849000   502000   205000    60000
  1957000   285000  1934000  2266000   389000   693000  5268000    81000
  1206000   136000   242000]

Name of the column: stocks
Number of unique values: 752
nunique values: [   28000   986000   900000  4687000  1404000  1780000   260000   103000
  1020000   212000   166000   612000   182000    30000   275000   223000
    81000  3570000  1218000   146000   308000  1781000  1402000    34000
    57000   247000  2100000   162000  3802000   930000   141000  2488000
   376000    65000  4896000    70000  1959000   232000   131000    97000
   637000    48000  2134000   150000   102000   307000   336000  4641000
  1132000  2268000   306000    62000  1535000   285000   412000   933000
   294000    23000   784000    40000  4320000  1617000   299000   326000
  1825000  1755000    68000   119000   219000  2557000    53000  4945000
   840000    54000  1071000   370000  6751000    90000  1361000   328000
    93000  1025000   207000  2422000   526000    92000  1024000  2774000
  9000000   982000  2734000   587000   158000  2304000   222000   352000
  2000000   688000   656000     9000  3273000  2011000   777000   517000
  4237000  2738000   171000   161000   396000  2246000   139000  7350000
   827000  1445000   528000  8736000   126000  3188000   699000   249000
   157000  1348000   280000  2797000   660000   159000  1485000  1688000
 12326000  1594000  4508000    66000  2220000   204000   489000  2301000
   390000    51000   865000   117000  3672000  2765000   898000   455000
  5472000  2240000   175000   167000   470000  2444000   151000  8832000
   702000    63000  1620000   698000 10901000   121000  1612000   557000
    86000   155000  5264000   524000   185000  1548000  2592000 10302000
  1436000  4186000   497000    32000  3110000   327000   437000  2028000
   854000    12000   821000    89000    50000  3475000  3210000   591000
  2135000  1965000   257000   154000   476000  2077000   104000  8836000
    49000  2026000   705000 13046000   106000  2799000   433000  1170000
   152000  4560000   746000   187000  1322000  3529000 11396000   957000
  2923000   125000  2679000   286000  1206000   520000  1334000   143000
    52000  2970000  3105000   649000   362000  5982000  2610000    95000
   200000   739000  2274000   243000 13340000   585000    64000  1665000
   554000 12796000  2986000   462000   211000  1151000   234000  4385000
   798000   235000  1142000  1872000  7735000   529000  3432000   188000
    84000  1610000   251000   213000   875000   530000    94000   572000
    55000  2827000  1859000   224000   381000  4578000  1115000    44000
    71000   525000   145000  9408000   505000   105000  1200000   514000
 12220000   147000  1533000   315000   917000   410000  3419000   468000
  1197000  1065000  3498000   576000    29000  1653000   130000   233000
   901000   407000    47000   347000   266000    21000  1885000  1110000
   281000  1097000  1161000    61000    74000   252000  2470000  8160000
   518000   803000   513000    14000  2410000   137000   985000   208000
   274000    69000   494000  2461000   383000    43000  1123000   810000
  6432000   722000  1491000   270000  1380000    78000   868000   447000
  1732000  1892000   246000   189000  1914000  1299000    46000   101000
   108000  1640000    79000  6803000   278000   964000   419000    13000
  2520000  1126000   144000   163000   942000   194000  2678000   474000
   282000   774000   388000  5792000   791000  2009000   648000    77000
   193000  1337000   683000   240000    37000  2439000  1924000   421000
  3773000  2043000   316000    45000   127000  1887000    72000  9126000
   353000  1111000 13545000    91000  1411000   531000   192000  1376000
   183000  2632000   380000   720000   571000  9300000   837000  2477000
   434000   283000  1793000   408000  1232000   611000  2519000  1598000
   346000   180000  3136000  2530000   442000   113000  2321000  8418000
   580000   800000 11818000   954000   331000   169000    59000  1935000
  2922000   291000   230000   839000   730000  7706000  1458000  1790000
   356000   107000  1441000   675000  2099000  3300000   453000  1981000
  3843000  2458000   215000  7770000   729000   605000 10575000    58000
   976000   265000   114000  1605000  2500000   209000   902000   717000
   892000  1363000   522000  1848000   374000   100000  1221000   196000
   413000  2350000  2564000  2203000  1477000    67000   138000  1947000
  9013000  1041000 10608000  1550000    96000  3024000   894000   214000
  4039000  1304000   312000   225000  1440000   116000   129000   128000
    27000  2021000  2569000   110000  4596000  1254000   122000  1260000
  8424000   371000   276000 11970000   149000   242000  2366000   562000
   301000  2109000  1428000   323000  1706000   339000   164000    25000
   610000  1505000  1427000    87000  3577000  1102000   978000  7623000
   132000   767000   319000  6237000   886000   198000    56000  1064000
    33000  1588000   391000    73000   665000   360000  6318000   533000
  1794000   239000  1179000   463000   288000  1524000  1774000  2905000
 12995000   874000   377000  4765000   792000   195000  1077000  1556000
   427000  3730000   443000   988000  1879000    98000   961000   471000
    17000  2084000    76000  3202000   653000   135000   153000  1235000
  7512000   228000   755000  4290000   633000   170000   836000  1508000
   253000  3119000   181000   263000   203000  1196000    41000    24000
  1332000  1591000  2413000  1146000    99000  5962000   845000   269000
  3604000   718000  1017000  1863000   459000  2505000   324000  1074000
  1036000    82000  1217000    39000   490000  1282000    85000  5231000
  1628000  1030000  6955000   456000  6381000  1689000    42000  1023000
    83000  1558000   558000    26000  2995000  1029000   140000   850000
   115000  1835000  1426000  5132000  1518000    88000  9271000   256000
    19000  5846000  2081000  1167000   255000   399000   832000   221000
  1082000   165000   990000   348000  1984000  2157000  3757000  1450000
   899000  9428000   357000   809000    38000  9379000  1164000  1603000
   261000   538000  1253000  1709000  1390000  3183000   640000  6809000
   664000   622000    36000 12127000  2607000  1205000   190000    22000
   197000  2198000   284000  1045000  1035000   279000   822000  1016000
   124000  2506000   423000   766000  4377000   657000   998000   177000
  6541000    75000  2297000   186000   109000  3022000   737000    18000
   655000  1005000   768000  3680000   833000  4752000   491000  1009000
   309000    15000  5154000    35000   563000   711000   201000   176000
  3216000   500000   830000   677000   428000  3063000  5802000  1027000
   118000  6422000  1141000   409000  7582000  1663000  1191000   692000
  2752000   883000   156000  1259000  1384000  2495000  3208000   250000
   844000   123000  8108000   392000  8668000   855000   608000   112000
   368000  1627000   849000   502000   205000    60000  1957000  1934000
   550000  2266000   389000   693000  5268000   384000   136000   750000]

Name of the column: average_price
Number of unique values: 425
nunique values: [ 62.    68.    64.    60.    63.    69.    55.    65.   102.    72.
  71.   103.    61.   100.   114.    66.    96.    81.    91.   128.
  83.    54.   116.    86.    84.    87.    79.    89.    80.    90.
 130.   107.    98.   127.   126.   111.   110.    85.    92.    88.
 105.   106.    94.    99.   113.   137.   108.   136.   169.    70.
  82.    73.   148.   159.    77.    74.    78.   104.   119.   147.
  75.   145.    76.    59.   140.    58.   165.   138.   124.   132.
 133.    56.    53.   115.    49.   164.   154.    57.   162.   134.
 117.   109.    52.    67.   135.   143.   150.   122.   172.   131.
 201.   158.   141.   155.   129.   112.   142.   156.   121.   175.
 118.   227.   160.   125.   186.   139.   173.   191.   146.   241.
 157.   190.   183.   195.   153.   192.   152.   144.   101.   193.
 123.   330.   218.   213.    97.    95.   212.   187.   209.   194.
 221.   188.   151.   220.   200.   149.   355.   161.   184.   219.
 240.   208.   360.   217.   225.   163.    93.   235.   196.   246.
 236.   178.   237.   204.   179.   198.   182.   226.   189.   273.
 252.   275.   199.   328.   267.   167.   278.   223.   202.   272.
 205.   180.   266.   228.   250.   310.   332.   239.   168.   251.
 365.   390.   214.   215.   317.   181.   170.   370.   283.   234.
 255.   293.   231.   407.   257.   247.   207.   415.   254.   315.
 203.   177.   280.   197.   339.   376.   216.   377.   238.   291.
 285.   211.   210.   419.   277.   245.   325.   314.   262.   367.
 329.   303.   389.   450.   230.   366.   353.   206.   229.   411.
 319.   396.   499.   249.   363.   313.   349.   358.   397.   224.
 489.   468.   261.   383.   243.   466.   323.   350.   404.   543.
 244.   420.   294.   451.   362.   410.   423.   553.   444.   345.
 185.   269.   542.   346.   304.   402.   338.   709.   478.   393.
 457.   176.   488.   364.   585.   392.   288.   300.   509.   361.
 403.   413.   500.   242.   874.   458.   324.   351.   270.   577.
 282.     3.72   3.01   1.88   2.11   2.05   2.4    2.76   1.92   1.96
   4.83   3.58   3.1    5.43   1.91   2.98   2.49   1.94   2.07   2.83
   1.9    2.01   7.47   3.24   5.76   1.87   2.36   3.89   3.17   4.11
   2.12   2.1    3.76   7.24   2.15   4.33   2.95   3.38   2.04   1.65
   1.6    2.34   2.46   2.67   1.3    1.62   4.12   3.78   2.35   4.66
   3.28   2.56   1.83   3.35   1.49   1.44   4.68   4.     1.43   3.46
   2.5    4.41   5.03   1.56   4.72   2.32   1.97   4.48   7.19   2.18
   4.26   3.     5.52   2.38   1.85   1.95   2.39   2.24   2.52   1.7
   1.76   5.65   3.91   2.54   3.25   3.36   1.8    1.99   3.59   1.61

In [ ]:
''' Find the state which appers the most number of times and mininum number of time '''

In [14]:
# The state which is appearing most number of times in dataset
df["state"].value_counts().idxmax()

'Alabama'

In [17]:
# The state which is appearing least number of times in dataset
df['state'].value_counts().idxmin()

'Oklahoma'

In [18]:
# top 5 most frequent states
df['state'].value_counts().head(5)

state
Alabama      27
Missouri     27
Arizona      27
NewJersey    27
NewYork      27
Name: count, dtype: int64

In [19]:
# top 10 most frequent states
df['state'].value_counts().head(10)

state
Alabama          27
Missouri         27
Arizona          27
NewJersey        27
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oregon           27
Pennsylvania     27
Name: count, dtype: int64

In [20]:
df['state'].value_counts()

state
Alabama          27
Missouri         27
Arizona          27
NewJersey        27
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oregon           27
Pennsylvania     27
SouthDakota      27
Tennessee        27
Texas            27
Utah             27
Vermont          27
Virginia         27
Washington       27
WestVirginia     27
Wisconsin        27
Montana          27
Nebraska         27
Mississippi      27
Minnesota        27
Arkansas         27
California       27
Colorado         27
Florida          27
Georgia          27
Hawaii           27
Idaho            27
Illinois         27
Indiana          27
Iowa             27
Kansas           27
Louisiana        27
Maine            27
Michigan         27
Wyoming          27
Kentucky         26
NewMexico        18
Nevada           15
SouthCarolina    12
Oklahoma          9
Maryland          9
Name: count, dtype: int64

In [21]:
# How many percentage of rows data belongs to each state?
df['state'].value_counts(normalize=True)*100
# df['state'] -> selects the state column
# .value_counts()  -> counts how many times each state appears.
# normalize=True  -> instead of normal count ,it converts them into proportions(fractions)
# * 100 -> converts proportions into percentages.

state
Alabama          2.421525
Missouri         2.421525
Arizona          2.421525
NewJersey        2.421525
NewYork          2.421525
NorthCarolina    2.421525
NorthDakota      2.421525
Ohio             2.421525
Oregon           2.421525
Pennsylvania     2.421525
SouthDakota      2.421525
Tennessee        2.421525
Texas            2.421525
Utah             2.421525
Vermont          2.421525
Virginia         2.421525
Washington       2.421525
WestVirginia     2.421525
Wisconsin        2.421525
Montana          2.421525
Nebraska         2.421525
Mississippi      2.421525
Minnesota        2.421525
Arkansas         2.421525
California       2.421525
Colorado         2.421525
Florida          2.421525
Georgia          2.421525
Hawaii           2.421525
Idaho            2.421525
Illinois         2.421525
Indiana          2.421525
Iowa             2.421525
Kansas           2.421525
Louisiana        2.421525
Maine            2.421525
Michigan         2.421525
Wyoming          2.421525
Kentucky         2.331839
NewMexico        1.614350
Nevada           1.345291
SouthCarolina    1.076233
Oklahoma         0.807175
Maryland         0.807175
Name: proportion, dtype: float64

In [22]:
# find total honey production per state
df.groupby('state')['production'].sum()

state
Alabama           14467000
Arizona           38844000
Arkansas          51846000
California       423876000
Colorado          32660000
Florida          280934000
Georgia           57426000
Hawaii            15420000
Idaho             87188000
Illinois           9864000
Indiana            9686000
Iowa              48607000
Kansas            14138000
Kentucky           3224000
Louisiana         60568000
Maine              4762000
Maryland           1975000
Michigan         101063000
Minnesota        176581000
Mississippi       21235000
Missouri          17904000
Montana          197173000
Nebraska          63655000
Nevada             7399000
NewJersey          6913000
NewMexico         10082000
NewYork           78444000
NorthCarolina      8909000
NorthDakota      513742000
Ohio              22485000
Oklahoma           2055000
Oregon            43789000
Pennsylvania      21370000
SouthCarolina      2823000
SouthDakota      355726000
Tennessee          6857000
Texas            129441000
Utah              20369000
Vermont            7032000
Virginia           5153000
Washington        53238000
WestVirginia       6411000
Wisconsin         99909000
Wyoming           43921000
Name: production, dtype: int64

In [23]:
# the state with highest honey production
df.groupby('state')['production'].sum().idxmax()

'NorthDakota'

In [24]:
df.groupby('state')['production'].sum().sort_values(ascending = False)

state
NorthDakota      513742000
California       423876000
SouthDakota      355726000
Florida          280934000
Montana          197173000
Minnesota        176581000
Texas            129441000
Michigan         101063000
Wisconsin         99909000
Idaho             87188000
NewYork           78444000
Nebraska          63655000
Louisiana         60568000
Georgia           57426000
Washington        53238000
Arkansas          51846000
Iowa              48607000
Wyoming           43921000
Oregon            43789000
Arizona           38844000
Colorado          32660000
Ohio              22485000
Pennsylvania      21370000
Mississippi       21235000
Utah              20369000
Missouri          17904000
Hawaii            15420000
Alabama           14467000
Kansas            14138000
NewMexico         10082000
Illinois           9864000
Indiana            9686000
NorthCarolina      8909000
Nevada             7399000
Vermont            7032000
NewJersey          6913000
Tennessee          6857000
WestVirginia       6411000
Virginia           5153000
Maine              4762000
Kentucky           3224000
SouthCarolina      2823000
Oklahoma           2055000
Maryland           1975000
Name: production, dtype: int64

In [25]:
df.columns

Index(['state', 'colonies_number', 'yield_per_colony', 'production', 'stocks',
       'average_price', 'value_of_production', 'year'],
      dtype='object')

In [26]:
# find average yield per colony per state
df.groupby('state')['yield_per_colony'].mean()

state
Alabama           59.814815
Arizona           55.185185
Arkansas          69.851852
California        52.814815
Colorado          56.296296
Florida           72.444444
Georgia           50.148148
Hawaii           103.777778
Idaho             41.518519
Illinois          57.851852
Indiana           59.444444
Iowa              61.444444
Kansas            58.148148
Kentucky          48.461538
Louisiana         92.814815
Maine             32.888889
Maryland          41.888889
Michigan          64.925926
Minnesota         69.814815
Mississippi       86.703704
Missouri          54.074074
Montana           79.555556
Nebraska          64.037037
Nevada            46.666667
NewJersey         35.481481
NewMexico         56.111111
NewYork           64.629630
NorthCarolina     45.777778
NorthDakota       83.925926
Ohio              65.296296
Oklahoma          52.333333
Oregon            42.407407
Pennsylvania      48.777778
SouthCarolina     60.583333
SouthDakota       72.222222
Tennessee         55.444444
Texas             71.148148
Utah              41.851852
Vermont           62.000000
Virginia          40.629630
Washington        46.481481
WestVirginia      46.111111
Wisconsin         70.222222
Wyoming           62.888889
Name: yield_per_colony, dtype: float64

In [27]:
# find max and min price per state
df.groupby('state')['average_price'].max()

state
Alabama          383.0
Arizona          203.0
Arkansas         206.0
California       216.0
Colorado         226.0
Florida          243.0
Georgia          300.0
Hawaii           415.0
Idaho            203.0
Illinois         542.0
Indiana          361.0
Iowa             245.0
Kansas           403.0
Kentucky         413.0
Louisiana        218.0
Maine            543.0
Maryland         191.0
Michigan         249.0
Minnesota        206.0
Mississippi      240.0
Missouri         370.0
Montana          221.0
Nebraska         207.0
Nevada           360.0
NewJersey        874.0
NewMexico        339.0
NewYork          319.0
NorthCarolina    478.0
NorthDakota      204.0
Ohio             393.0
Oklahoma         183.0
Oregon           243.0
Pennsylvania     362.0
SouthCarolina    457.0
SouthDakota      208.0
Tennessee        488.0
Texas            224.0
Utah             213.0
Vermont          489.0
Virginia         585.0
Washington       261.0
WestVirginia     444.0
Wisconsin        282.0
Wyoming          211.0
Name: average_price, dtype: float64

In [30]:
df.groupby('state')['average_price'].max().sort_values(ascending = False).head()

state
NewJersey    874.0
Virginia     585.0
Maine        543.0
Illinois     542.0
Vermont      489.0
Name: average_price, dtype: float64

In [28]:
df.groupby('state')['average_price'].min()

state
Alabama            3.38
Arizona            2.04
Arkansas           1.65
California         1.60
Colorado           2.05
Florida            2.24
Georgia            2.52
Hawaii             1.30
Idaho              1.62
Illinois           4.12
Indiana            3.58
Iowa               2.35
Kansas             2.35
Kentucky           4.60
Louisiana          1.91
Maine              2.98
Maryland         110.00
Michigan           2.49
Minnesota          1.80
Mississippi        1.87
Missouri           2.83
Montana            1.49
Nebraska           1.44
Nevada            96.00
NewJersey          3.27
NewMexico         65.00
NewYork            3.13
NorthCarolina      4.11
NorthDakota        1.43
Ohio               3.46
Oklahoma          91.00
Oregon             2.14
Pennsylvania       3.40
SouthCarolina      3.17
SouthDakota        1.56
Tennessee          4.11
Texas              2.00
Utah               1.97
Vermont            3.28
Virginia           6.03
Washington         2.15
WestVirginia       3.81
Wisconsin          2.81
Wyoming            1.43
Name: average_price, dtype: float64

In [33]:
df.groupby('state')['average_price'].min().sort_values(ascending = False).head()

state
Maryland     110.00
Nevada        96.00
Oklahoma      91.00
NewMexico     65.00
Virginia       6.03
Name: average_price, dtype: float64

In [35]:
df.columns

Index(['state', 'colonies_number', 'yield_per_colony', 'production', 'stocks',
       'average_price', 'value_of_production', 'year'],
      dtype='object')

In [36]:
''' on the basis of state column find total production per state,
    average price per state and total value of prouduction per state '''

df.groupby('state').agg({
    'production':'sum',
    'average_price':'mean',
    'value_of_production':'sum'
})

               production  average_price  value_of_production
state
Alabama          14467000     150.281852             28668000
Arizona          38844000     110.324815             59772000
Arkansas         51846000     106.312963             73781000
California      423876000     109.409630            653982000
Colorado         32660000     118.539259             63844000
Florida         280934000     109.908148            509670000
Georgia          57426000     120.765926            145945000
Hawaii           15420000     137.745556             49888000
Idaho            87188000     106.285556            139536000
Illinois          9864000     216.386296             36782000
Indiana           9686000     154.931852             24658000
Iowa             48607000     123.768519             87563000
Kansas           14138000     147.312593             27970000
Kentucky          3224000     201.940385             15427000
Louisiana        60568000     103.074815            129601000
Maine             4762000     173.770370             19842000
Maryland          1975000     145.555556              2735000
Michigan        101063000     122.665556            217841000
Minnesota       176581000     106.958889            310462000
Mississippi      21235000     102.840741             59265000
Missouri         17904000     145.991111             32372000
Montana         197173000     109.672963            406563000
Nebraska         63655000     111.270741            106998000
Nevada            7399000     204.533333             14520000
NewJersey         6913000     194.916296             28201000
NewMexico        10082000     122.055556             11049000
NewYork          78444000     135.685926            177921000
NorthCarolina     8909000     205.192963             38645000
NorthDakota     513742000     106.040000           1186219000
Ohio             22485000     163.606667             59637000
Oklahoma          2055000     133.666667              2618000
Oregon           43789000     119.311111            102109000
Pennsylvania     21370000     152.993333             55153000
SouthCarolina     2823000     175.996667             26218000
SouthDakota     355726000     107.092963            619095000
Tennessee         6857000     196.965185             27276000
Texas           129441000     109.842222            284720000
Utah             20369000     111.232222             40157000
Vermont           7032000     173.683704             19084000
Virginia          5153000     237.766296             20925000
Washington       53238000     118.828148            119823000
WestVirginia      6411000     191.192593             18685000
Wisconsin        99909000     126.328519            176442000
Wyoming          43921000     107.560000             87502000

In [38]:
# give custom_names to the columns and sort the data wrt to any column

df.groupby('state').agg(
    Total_productions = ('production','sum'),
    Average_price = ('average_price','mean'),
    Total_value = ('value_of_production','sum')
).sort_values("Total_productions", ascending = False)

               Total_productions  Average_price  Total_value
state
NorthDakota            513742000     106.040000   1186219000
California             423876000     109.409630    653982000
SouthDakota            355726000     107.092963    619095000
Florida                280934000     109.908148    509670000
Montana                197173000     109.672963    406563000
Minnesota              176581000     106.958889    310462000
Texas                  129441000     109.842222    284720000
Michigan               101063000     122.665556    217841000
Wisconsin               99909000     126.328519    176442000
Idaho                   87188000     106.285556    139536000
NewYork                 78444000     135.685926    177921000
Nebraska                63655000     111.270741    106998000
Louisiana               60568000     103.074815    129601000
Georgia                 57426000     120.765926    145945000
Washington              53238000     118.828148    119823000
Arkansas                51846000     106.312963     73781000
Iowa                    48607000     123.768519     87563000
Wyoming                 43921000     107.560000     87502000
Oregon                  43789000     119.311111    102109000
Arizona                 38844000     110.324815     59772000
Colorado                32660000     118.539259     63844000
Ohio                    22485000     163.606667     59637000
Pennsylvania            21370000     152.993333     55153000
Mississippi             21235000     102.840741     59265000
Utah                    20369000     111.232222     40157000
Missouri                17904000     145.991111     32372000
Hawaii                  15420000     137.745556     49888000
Alabama                 14467000     150.281852     28668000
Kansas                  14138000     147.312593     27970000
NewMexico               10082000     122.055556     11049000
Illinois                 9864000     216.386296     36782000
Indiana                  9686000     154.931852     24658000
NorthCarolina            8909000     205.192963     38645000
Nevada                   7399000     204.533333     14520000
Vermont                  7032000     173.683704     19084000
NewJersey                6913000     194.916296     28201000
Tennessee                6857000     196.965185     27276000
WestVirginia             6411000     191.192593     18685000
Virginia                 5153000     237.766296     20925000
Maine                    4762000     173.770370     19842000
Kentucky                 3224000     201.940385     15427000
SouthCarolina            2823000     175.996667     26218000
Oklahoma                 2055000     133.666667      2618000
Maryland                 1975000     145.555556      2735000

In [40]:
# find the states which are having high production but they are having low average price

df1 = df.groupby('state').agg({
    'production':'sum',
    'average_price':'mean'
})

mean_prod = df1['production'].mean()
mean_price = df1['average_price'].mean()

df1[(df1['production']>df1['production'].mean())&(df1['average_price']<df1['average_price'].mean())]
# both the commands will give same output

df1[(df1['production']>mean_prod)&(df1['average_price']<mean_price)]

             production  average_price
state
California    423876000     109.409630
Florida       280934000     109.908148
Idaho          87188000     106.285556
Michigan      101063000     122.665556
Minnesota     176581000     106.958889
Montana       197173000     109.672963
NewYork        78444000     135.685926
NorthDakota   513742000     106.040000
SouthDakota   355726000     107.092963
Texas         129441000     109.842222
Wisconsin      99909000     126.328519

In [41]:
# which state is most efficient?
# production , yield per colony / number of colonies
# production - stock / colonies

state_eff = df.groupby('state').agg({
    'production':'mean',
    'colonies_number':'mean'
})
print(state_eff)

                 production  colonies_number
state
Alabama        5.358148e+05     10666.666667
Arizona        1.438667e+06     31629.629630
Arkansas       1.920222e+06     33629.629630
California     1.569911e+07    375370.370370
Colorado       1.209630e+06     29592.592593
Florida        1.040496e+07    204740.740741
Georgia        2.126889e+06     71000.000000
Hawaii         5.711111e+05     10962.962963
Idaho          3.229185e+06    100185.185185
Illinois       3.653333e+05      8740.740741
Indiana        3.587407e+05      7888.888889
Iowa           1.800259e+06     35629.629630
Kansas         5.236296e+05     11148.148148
Kentucky       1.240000e+05      4346.153846
Louisiana      2.243259e+06     39481.481481
Maine          1.763704e+05      9333.333333
Maryland       2.194444e+05      5333.333333
Michigan       3.743074e+06     80296.296296
Minnesota      6.540037e+06    129555.555556
Mississippi    7.864815e+05     17962.962963
Missouri       6.631111e+05     14444.444444
Montana        7.302704e+06    137962.962963
Nebraska       2.357593e+06     47370.370370
Nevada         4.932667e+05     10466.666667
NewJersey      2.560370e+05     11074.074074
NewMexico      5.601111e+05     10277.777778
NewYork        2.905333e+06     58814.814815
NorthCarolina  3.299630e+05     11259.259259
NorthDakota    1.902748e+07    396666.666667
Ohio           8.327778e+05     16629.629630
Oklahoma       2.283333e+05      4444.444444
Oregon         1.621815e+06     59037.037037
Pennsylvania   7.914815e+05     21703.703704
SouthCarolina  2.352500e+05     12333.333333
SouthDakota    1.317504e+07    245888.888889
Tennessee      2.539630e+05      7000.000000
Texas          4.794111e+06    106518.518519
Utah           7.544074e+05     26629.629630
Vermont        2.604444e+05      5518.518519
Virginia       1.908519e+05      6296.296296
Washington     1.971778e+06     63296.296296
WestVirginia   2.374444e+05      6629.629630
Wisconsin      3.700333e+06     62888.888889
Wyoming        1.626704e+06     39444.444444

In [42]:
state_eff['efficiency'] = state_eff['production']/state_eff['colonies_number']
print(state_eff)

                 production  colonies_number  efficiency
state
Alabama        5.358148e+05     10666.666667   50.232639
Arizona        1.438667e+06     31629.629630   45.484778
Arkansas       1.920222e+06     33629.629630   57.099119
California     1.569911e+07    375370.370370   41.822990
Colorado       1.209630e+06     29592.592593   40.876095
Florida        1.040496e+07    204740.740741   50.820188
Georgia        2.126889e+06     71000.000000   29.956182
Hawaii         5.711111e+05     10962.962963   52.094595
Idaho          3.229185e+06    100185.185185   32.232163
Illinois       3.653333e+05      8740.740741   41.796610
Indiana        3.587407e+05      7888.888889   45.474178
Iowa           1.800259e+06     35629.629630   50.527027
Kansas         5.236296e+05     11148.148148   46.970100
Kentucky       1.240000e+05      4346.153846   28.530973
Louisiana      2.243259e+06     39481.481481   56.818011
Maine          1.763704e+05      9333.333333   18.896825
Maryland       2.194444e+05      5333.333333   41.145833
Michigan       3.743074e+06     80296.296296   46.615775
Minnesota      6.540037e+06    129555.555556   50.480560
Mississippi    7.864815e+05     17962.962963   43.783505
Missouri       6.631111e+05     14444.444444   45.907692
Montana        7.302704e+06    137962.962963   52.932349
Nebraska       2.357593e+06     47370.370370   49.769351
Nevada         4.932667e+05     10466.666667   47.127389
NewJersey      2.560370e+05     11074.074074   23.120401
NewMexico      5.601111e+05     10277.777778   54.497297
NewYork        2.905333e+06     58814.814815   49.397985
NorthCarolina  3.299630e+05     11259.259259   29.305921
NorthDakota    1.902748e+07    396666.666667   47.968441
Ohio           8.327778e+05     16629.629630   50.077951
Oklahoma       2.283333e+05      4444.444444   51.375000
Oregon         1.621815e+06     59037.037037   27.471142
Pennsylvania   7.914815e+05     21703.703704   36.467577
SouthCarolina  2.352500e+05     12333.333333   19.074324
SouthDakota    1.317504e+07    245888.888889   53.581262
Tennessee      2.539630e+05      7000.000000   36.280423
Texas          4.794111e+06    106518.518519   45.007302
Utah           7.544074e+05     26629.629630   28.329624
Vermont        2.604444e+05      5518.518519   47.194631
Virginia       1.908519e+05      6296.296296   30.311765
Washington     1.971778e+06     63296.296296   31.151551
WestVirginia   2.374444e+05      6629.629630   35.815642
Wisconsin      3.700333e+06     62888.888889   58.839223
Wyoming        1.626704e+06     39444.444444   41.240376

In [44]:
state_eff.sort_values('efficiency', ascending = False)

                 production  colonies_number  efficiency
state
Wisconsin      3.700333e+06     62888.888889   58.839223
Arkansas       1.920222e+06     33629.629630   57.099119
Louisiana      2.243259e+06     39481.481481   56.818011
NewMexico      5.601111e+05     10277.777778   54.497297
SouthDakota    1.317504e+07    245888.888889   53.581262
Montana        7.302704e+06    137962.962963   52.932349
Hawaii         5.711111e+05     10962.962963   52.094595
Oklahoma       2.283333e+05      4444.444444   51.375000
Florida        1.040496e+07    204740.740741   50.820188
Iowa           1.800259e+06     35629.629630   50.527027
Minnesota      6.540037e+06    129555.555556   50.480560
Alabama        5.358148e+05     10666.666667   50.232639
Ohio           8.327778e+05     16629.629630   50.077951
Nebraska       2.357593e+06     47370.370370   49.769351
NewYork        2.905333e+06     58814.814815   49.397985
NorthDakota    1.902748e+07    396666.666667   47.968441
Vermont        2.604444e+05      5518.518519   47.194631
Nevada         4.932667e+05     10466.666667   47.127389
Kansas         5.236296e+05     11148.148148   46.970100
Michigan       3.743074e+06     80296.296296   46.615775
Missouri       6.631111e+05     14444.444444   45.907692
Arizona        1.438667e+06     31629.629630   45.484778
Indiana        3.587407e+05      7888.888889   45.474178
Texas          4.794111e+06    106518.518519   45.007302
Mississippi    7.864815e+05     17962.962963   43.783505
California     1.569911e+07    375370.370370   41.822990
Illinois       3.653333e+05      8740.740741   41.796610
Wyoming        1.626704e+06     39444.444444   41.240376
Maryland       2.194444e+05      5333.333333   41.145833
Colorado       1.209630e+06     29592.592593   40.876095
Pennsylvania   7.914815e+05     21703.703704   36.467577
Tennessee      2.539630e+05      7000.000000   36.280423
WestVirginia   2.374444e+05      6629.629630   35.815642
Idaho          3.229185e+06    100185.185185   32.232163
Washington     1.971778e+06     63296.296296   31.151551
Virginia       1.908519e+05      6296.296296   30.311765
Georgia        2.126889e+06     71000.000000   29.956182
NorthCarolina  3.299630e+05     11259.259259   29.305921
Kentucky       1.240000e+05      4346.153846   28.530973
Utah           7.544074e+05     26629.629630   28.329624
Oregon         1.621815e+06     59037.037037   27.471142
NewJersey      2.560370e+05     11074.074074   23.120401
SouthCarolina  2.352500e+05     12333.333333   19.074324
Maine          1.763704e+05      9333.333333   18.896825

In [47]:
# this method is used to ignore the decimal error
if np.allclose(df['yield_per_colony'], df['production']/df['colonies_number']):
    print("They are same")
else:
    print("the values are different and we can say that yes the yield per colony is an average value")

the values are different and we can say that yes the yield per colony is an average value

In [48]:
df[['production','yield_per_colony']].corr()

                  production  yield_per_colony
production           1.00000           0.41341
yield_per_colony     0.41341           1.00000